steps:
  - block: "Continue with input"
    prompt: "Fill out the form below!"
    fields:
      - text: "What version is this? :parrot:"
        key: "version"
        default: "This is the default value"
        hint: "This is a hint :ruby:"
      - select: "Choose on of these"
        key: "deploy-target"
        options:
          - Staging
          - QA1
          - QA2
          - Poes
          - Production
      - select: "Would you like a :taco: after this deploy?"
        hint: "Less than 6 options will show a radio, more than 6 will show a select box"
        key: "taco"
        default: "Yes"
        options:
          - "Yes"
          - "No"
          - ":llama:"
      - select: "What team should be notified after the deployment?"
        key: "notify-team"
        hint: "Another great hint here"
        options:
          - All
          - None
          - Billing
          - Ops
          - Sales
          - Directors
          - Engineering
          - Support
          - QA

  - label: ":console:"
    command: ".buildkite/results.sh"

  - block: "Continue without input"

  - label: ":console:"
    command: >
      echo "Sadness..."
